const PAYROLL_ROLES = ['admin', 'super_admin', 'developer']
const PAYROLL_ADJUSTMENT_ROLES = ['hr', 'accounts', 'admin', 'super_admin', 'developer']

const payrollMeta = (title, feature, roles = PAYROLL_ROLES) => ({
  requiresAuth: true,
  roles,
  feature,
  title,
})

export const payrollRoutes = [
  {
    path: '/payroll/salary-structures',
    name: 'PayrollSalaryStructureList',
    component: () => import('@/views/admin-pages/payroll/SalaryStructureList.vue'),
    meta: payrollMeta('Salary Structures', 'payroll.salary_structures.view'),
  },
  {
    path: '/payroll/salary-structures/create',
    name: 'PayrollSalaryStructureCreate',
    component: () => import('@/views/admin-pages/payroll/SalaryStructureForm.vue'),
    meta: payrollMeta('Create Salary Structure', 'payroll.salary_structures.manage'),
  },
  {
    path: '/payroll/salary-structures/:id/edit',
    name: 'PayrollSalaryStructureEdit',
    component: () => import('@/views/admin-pages/payroll/SalaryStructureForm.vue'),
    props: true,
    meta: payrollMeta('Edit Salary Structure', 'payroll.salary_structures.manage'),
  },
  {
    path: '/payroll/salary-revisions/create',
    name: 'PayrollSalaryRevisionCreate',
    component: () => import('@/views/admin-pages/payroll/SalaryRevisionForm.vue'),
    meta: payrollMeta('Salary Revision', 'payroll.salary_revisions.manage'),
  },
  {
    path: '/payroll/meal-entries',
    name: 'PayrollMealEntryList',
    component: () => import('@/views/admin-pages/payroll/MealEntryList.vue'),
    meta: payrollMeta('Meal Entries', 'payroll.meal_entries.view'),
  },
  {
    path: '/payroll/meal-entries/create',
    name: 'PayrollMealEntryCreate',
    component: () => import('@/views/admin-pages/payroll/MealEntryCreate.vue'),
    meta: payrollMeta('Bulk Meal Entry', 'payroll.meal_entries.manage'),
  },
  {
    path: '/payroll/employee-loans',
    name: 'PayrollEmployeeLoanList',
    component: () => import('@/views/admin-pages/payroll/EmployeeLoanList.vue'),
    meta: payrollMeta('Employee Loans', 'payroll.loans.view'),
  },
  {
    path: '/payroll/arrear-entries',
    name: 'PayrollArrearEntryList',
    component: () => import('@/views/admin-pages/payroll/PayrollArrearEntryList.vue'),
    meta: payrollMeta('Payroll Arrears', 'payroll.arrears.view'),
  },
  {
    path: '/payroll/advance-deductions',
    name: 'PayrollAdvanceDeductionList',
    component: () => import('@/views/admin-pages/payroll/PayrollAdvanceDeductionList.vue'),
    meta: payrollMeta('Advance Deductions', 'payroll.advance_deductions.view'),
  },
  {
    path: '/payroll/advance-deductions/create',
    name: 'PayrollAdvanceDeductionCreate',
    component: () => import('@/views/admin-pages/payroll/PayrollAdvanceDeductionCreate.vue'),
    meta: payrollMeta('Bulk Advance Deduction', 'payroll.advance_deductions.manage'),
  },
  {
    path: '/payroll/advance-deductions/:id',
    name: 'PayrollAdvanceDeductionShow',
    component: () => import('@/views/admin-pages/payroll/PayrollAdvanceDeductionShow.vue'),
    props: true,
    meta: payrollMeta('Advance Deduction Slip', 'payroll.advance_deductions.view'),
  },
  {
    path: '/payroll/arrear-entries/create',
    name: 'PayrollArrearEntryCreate',
    component: () => import('@/views/admin-pages/payroll/PayrollArrearEntryCreate.vue'),
    meta: payrollMeta('Bulk Arrear Entry', 'payroll.arrears.manage'),
  },
  {
    path: '/payroll/security-monies',
    name: 'PayrollSecurityMoneyList',
    component: () => import('@/views/admin-pages/payroll/SecurityMoneyList.vue'),
    meta: payrollMeta('Security Money', 'payroll.security_money.view'),
  },
  {
    path: '/payroll/employee-loans/:id',
    name: 'PayrollEmployeeLoanShow',
    component: () => import('@/views/admin-pages/payroll/EmployeeLoanShow.vue'),
    props: true,
    meta: payrollMeta('Loan Details', 'payroll.loans.view'),
  },
  {
    path: '/payroll/batches',
    name: 'PayrollBatchList',
    component: () => import('@/views/admin-pages/payroll/PayrollBatchList.vue'),
    meta: payrollMeta('Payroll Batches', 'payroll.batches.view'),
  },
  {
    path: '/payroll/batches/generate',
    name: 'PayrollBatchGenerate',
    component: () => import('@/views/admin-pages/payroll/GeneratePayrollForm.vue'),
    meta: payrollMeta('Generate Payroll', 'payroll.batches.generate'),
  },
  {
    path: '/payroll/batches/:id',
    name: 'PayrollBatchShow',
    component: () => import('@/views/admin-pages/payroll/PayrollBatchShow.vue'),
    props: true,
    meta: payrollMeta('Batch Details', 'payroll.batches.view'),
  },
  {
    path: '/payrolls',
    name: 'PayrollList',
    component: () => import('@/views/admin-pages/payroll/PayrollList.vue'),
    meta: payrollMeta('Payrolls', 'payroll.reports.view'),
  },
  {
    path: '/payrolls/doctors',
    name: 'DoctorPayrollList',
    component: () => import('@/views/admin-pages/payroll/DoctorPayrollList.vue'),
    meta: payrollMeta('Doctor Payrolls', 'payroll.doctor.view'),
  },
  {
    path: '/payrolls/bank-advisers',
    name: 'PayrollBankAdviserList',
    component: () => import('@/views/admin-pages/payroll/BankAdviserList.vue'),
    meta: payrollMeta('Bank Advise', 'payroll.bank_adviser.view'),
  },
  {
    path: '/payrolls/cash-slips',
    name: 'PayrollSlipList',
    component: () => import('@/views/admin-pages/payroll/PayrollSlipList.vue'),
    meta: payrollMeta('Payroll Slip List', 'payroll.slips.view'),
  },
  {
    path: '/payrolls/cash-slips/:id',
    name: 'PayrollSlipShow',
    component: () => import('@/views/admin-pages/payroll/PayrollSlipShow.vue'),
    props: true,
    meta: payrollMeta('Payroll Slip', 'payroll.slips.view'),
  },
  {
    path: '/payrolls/:id',
    name: 'PayrollShow',
    component: () => import('@/views/admin-pages/payroll/PayrollShow.vue'),
    props: true,
    meta: payrollMeta('Payroll Details', 'payroll.reports.view'),
  },
  {
    path: '/payroll/adjustments',
    name: 'PayrollAdjustmentList',
    component: () => import('@/pages/payroll/adjustments/index.vue'),
    meta: payrollMeta('Payroll Adjustments', 'payroll.adjustments.view', PAYROLL_ADJUSTMENT_ROLES),
  },
  {
    path: '/payroll/adjustments/create',
    name: 'PayrollAdjustmentCreate',
    component: () => import('@/pages/payroll/adjustments/create.vue'),
    meta: payrollMeta('Create Adjustment', 'payroll.adjustments.manage', PAYROLL_ADJUSTMENT_ROLES),
  },
  {
    path: '/payroll/adjustments/carry-forward/preview',
    name: 'PayrollAdjustmentCarryPreview',
    component: () => import('@/pages/payroll/adjustments/carry-forward/preview.vue'),
    meta: payrollMeta('Carry Forward Preview', 'payroll.adjustments.manage', PAYROLL_ADJUSTMENT_ROLES),
  },
  {
    path: '/payroll/adjustments/:id',
    name: 'PayrollAdjustmentShow',
    component: () => import('@/pages/payroll/adjustments/[id].vue'),
    props: true,
    meta: payrollMeta('Adjustment Details', 'payroll.adjustments.view', PAYROLL_ADJUSTMENT_ROLES),
  },
]
