const PAYROLL_ROLES = ['admin', 'super_admin', 'developer']
const PAYROLL_ADJUSTMENT_ROLES = ['hr', 'accounts', 'admin', 'super_admin', 'developer']

export const payrollRoutes = [
  {
    path: '/payroll/salary-structures',
    name: 'PayrollSalaryStructureList',
    component: () => import('@/views/admin-pages/payroll/SalaryStructureList.vue'),
    meta: { requiresAuth: true, roles: PAYROLL_ROLES, title: 'Salary Structures' },
  },
  {
    path: '/payroll/salary-structures/create',
    name: 'PayrollSalaryStructureCreate',
    component: () => import('@/views/admin-pages/payroll/SalaryStructureForm.vue'),
    meta: { requiresAuth: true, roles: PAYROLL_ROLES, title: 'Create Salary Structure' },
  },
  {
    path: '/payroll/salary-structures/:id/edit',
    name: 'PayrollSalaryStructureEdit',
    component: () => import('@/views/admin-pages/payroll/SalaryStructureForm.vue'),
    props: true,
    meta: { requiresAuth: true, roles: PAYROLL_ROLES, title: 'Edit Salary Structure' },
  },
  {
    path: '/payroll/salary-revisions/create',
    name: 'PayrollSalaryRevisionCreate',
    component: () => import('@/views/admin-pages/payroll/SalaryRevisionForm.vue'),
    meta: { requiresAuth: true, roles: PAYROLL_ROLES, title: 'Salary Revision' },
  },
  {
    path: '/payroll/meal-entries',
    name: 'PayrollMealEntryList',
    component: () => import('@/views/admin-pages/payroll/MealEntryList.vue'),
    meta: { requiresAuth: true, roles: PAYROLL_ROLES, title: 'Meal Entries' },
  },
  {
    path: '/payroll/meal-entries/create',
    name: 'PayrollMealEntryCreate',
    component: () => import('@/views/admin-pages/payroll/MealEntryCreate.vue'),
    meta: { requiresAuth: true, roles: PAYROLL_ROLES, title: 'Bulk Meal Entry' },
  },
  {
    path: '/payroll/employee-loans',
    name: 'PayrollEmployeeLoanList',
    component: () => import('@/views/admin-pages/payroll/EmployeeLoanList.vue'),
    meta: { requiresAuth: true, roles: PAYROLL_ROLES, title: 'Employee Loans' },
  },
  {
    path: '/payroll/employee-loans/:id',
    name: 'PayrollEmployeeLoanShow',
    component: () => import('@/views/admin-pages/payroll/EmployeeLoanShow.vue'),
    props: true,
    meta: { requiresAuth: true, roles: PAYROLL_ROLES, title: 'Loan Details' },
  },
  {
    path: '/payroll/batches',
    name: 'PayrollBatchList',
    component: () => import('@/views/admin-pages/payroll/PayrollBatchList.vue'),
    meta: { requiresAuth: true, roles: PAYROLL_ROLES, title: 'Payroll Batches' },
  },
  {
    path: '/payroll/batches/generate',
    name: 'PayrollBatchGenerate',
    component: () => import('@/views/admin-pages/payroll/GeneratePayrollForm.vue'),
    meta: { requiresAuth: true, roles: PAYROLL_ROLES, title: 'Generate Payroll' },
  },
  {
    path: '/payroll/batches/:id',
    name: 'PayrollBatchShow',
    component: () => import('@/views/admin-pages/payroll/PayrollBatchShow.vue'),
    props: true,
    meta: { requiresAuth: true, roles: PAYROLL_ROLES, title: 'Batch Details' },
  },
  {
    path: '/payrolls',
    name: 'PayrollList',
    component: () => import('@/views/admin-pages/payroll/PayrollList.vue'),
    meta: { requiresAuth: true, roles: PAYROLL_ROLES, title: 'Payrolls' },
  },
  {
    path: '/payrolls/doctors',
    name: 'DoctorPayrollList',
    component: () => import('@/views/admin-pages/payroll/DoctorPayrollList.vue'),
    meta: { requiresAuth: true, roles: PAYROLL_ROLES, title: 'Doctor Payrolls' },
  },
  {
    path: '/payrolls/bank-advisers',
    name: 'PayrollBankAdviserList',
    component: () => import('@/views/admin-pages/payroll/BankAdviserList.vue'),
    meta: { requiresAuth: true, roles: PAYROLL_ROLES, title: 'Bank Adviser List' },
  },
  {
    path: '/payrolls/cash-slips',
    name: 'PayrollSlipList',
    component: () => import('@/views/admin-pages/payroll/PayrollSlipList.vue'),
    meta: { requiresAuth: true, roles: PAYROLL_ROLES, title: 'Payroll Slip List' },
  },
  {
    path: '/payrolls/cash-slips/:id',
    name: 'PayrollSlipShow',
    component: () => import('@/views/admin-pages/payroll/PayrollSlipShow.vue'),
    props: true,
    meta: { requiresAuth: true, roles: PAYROLL_ROLES, title: 'Payroll Slip' },
  },
  {
    path: '/payrolls/:id',
    name: 'PayrollShow',
    component: () => import('@/views/admin-pages/payroll/PayrollShow.vue'),
    props: true,
    meta: { requiresAuth: true, roles: PAYROLL_ROLES, title: 'Payroll Details' },
  },
  {
    path: '/payroll/adjustments',
    name: 'PayrollAdjustmentList',
    component: () => import('@/pages/payroll/adjustments/index.vue'),
    meta: { requiresAuth: true, roles: PAYROLL_ADJUSTMENT_ROLES, title: 'Payroll Adjustments' },
  },
  {
    path: '/payroll/adjustments/create',
    name: 'PayrollAdjustmentCreate',
    component: () => import('@/pages/payroll/adjustments/create.vue'),
    meta: { requiresAuth: true, roles: PAYROLL_ADJUSTMENT_ROLES, title: 'Create Adjustment' },
  },
  {
    path: '/payroll/adjustments/carry-forward/preview',
    name: 'PayrollAdjustmentCarryPreview',
    component: () => import('@/pages/payroll/adjustments/carry-forward/preview.vue'),
    meta: { requiresAuth: true, roles: PAYROLL_ADJUSTMENT_ROLES, title: 'Carry Forward Preview' },
  },
  {
    path: '/payroll/adjustments/:id',
    name: 'PayrollAdjustmentShow',
    component: () => import('@/pages/payroll/adjustments/[id].vue'),
    props: true,
    meta: { requiresAuth: true, roles: PAYROLL_ADJUSTMENT_ROLES, title: 'Adjustment Details' },
  },
]
